#!/bin/bash
set -u

cd "${BASH_SOURCE%/*}"

mkdir -p AppDir/usr/bin

cp -r ../data AppDir
rm -rf AppDir/data/screenshots
cp AppRun AppDir
cp ../chronomi.bin AppDir/usr/bin
cp ../data/chronomi.png AppDir
cp ../data/chronomi.desktop AppDir

./linuxdeploy-x86_64.AppImage --appdir=AppDir --output=appimage

wait

rm -rf AppDir
